cat <<EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svn-test-deployment
  labels:
    app: svn-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svn-test
  template:
    metadata:
      labels:
        app: svn-test
    spec:
      securityContext:
        runAsUser: 1001      # The user ID the container entrypoint will run as
        runAsGroup: 3001      # The primary group ID for the container process
        fsGroup: 2000         # The group ID for ownership of mounted volumes
      allowPrivilegeEscalation: false
      containers:
        - name: main
          image: quay.io/johnibm/svn-server:v1
          # Keep container running
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      imagePullPolicy: Always
EOF

