cat <<EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svn-test-deployment
  namespace: demo-svn
  labels:
    app: svn-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svn-test
  template:
    metadata:
      labels:
        app: svn-test
    spec:
      securityContext:
        runAsUser: 1001      # The user ID the container entrypoint will run as
        runAsGroup: 3001      # The primary group ID for the container process
        #fsGroup: 2000         # The group ID for ownership of mounted volumes
      allowPrivilegeEscalation: false
      containers:
        - name: main
          image: quay.io/johnibm/svn-server:v1
          # Keep container running
          command: [ "/bin/sh", "-c", "--" ]
          args: ['echo "Starting main container" &&\
                echo "Run Script" &&\
                /app/usr/bin/startup.sh &&\
                sleep 30 &&\
                echo "Startup Script finished. Pod will now stay alive." &&\
                tail -f /dev/null']
          imagePullPolicy: Always
EOF



cat <<EOF | oc apply -f -
apiVersion: v1
kind: Service
metadata:
  name: svn-test-http-svc
  namespace: demo-svn
  labels:
    app: svn-test
spec:
  type: ClusterIP
  selector:
    app: svn-test
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
EOF



cat <<EOF | oc apply -f -
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: svn-test
  namespace: demo-svn
spec:
  to:
    kind: Service
    name: svn-test-http
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge   # change to 'passthrough' or 'reencrypt' for TLS needs
EOF